import type { GetServerSideProps, NextPage } from "next";
import dynamic from "next/dynamic";

import Head from "next/head";
import { styled } from "@mui/material/styles";
import Layout from "../shared/layout/Layout";
import { wrapper } from "../app/store";
import { user } from "../features/user/hocs/authorize";
import { User } from "../features/user/models/user";
import { useAppSelector } from "../app/hooks";
import { getCurrentUserProfile } from "../features/user/redux/userSlice";
import { getCourses } from "../features/course/redux/courseSlice";
import { getCart } from "../features/cart/redux/cartSlice";
// Dynamicaly import the AuthGuard component.
const AuthGuard = dynamic(() =>
  import("../features/user/components/AuthGuard").then((mod) => mod.AuthGuard)
);

//const CustomButton = styled("Button")();

interface IProps {
  user: User;
}
const Home: NextPage = () => {
  return (
    <AuthGuard restricted={false}>
      <Layout>
        <Head>
          <title>Dashboard Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>Welcome to Dashbaord </p>
      </Layout>
    </AuthGuard>
  );
};

export const getServerSideProps: GetServerSideProps = user({
  callback: async (accessToken, store) => {
    // await store.dispatch(getCart());
    console.log("Inside Index Page");

    return { props: {} };
  },
});
export default Home;
